export const translations = {
  en: {
    nav: { shop: 'Shop', brands: 'Brands', blog: 'Blog', about: 'About', faq: 'FAQ', cart: 'Cart' },
    hero: {
      title: 'Premium Silicone & TPE Love Dolls',
      subtitle: 'Authentic European-style and anime dolls. Discreet shipping across Europe. Free shipping on orders over €500.',
      cta: 'Shop Now'
    },
    trust: {
      authentic: '100% Authentic', authenticDesc: 'Direct from manufacturer with anti-counterfeit code',
      shipping: 'Discreet Shipping', shippingDesc: 'Plain boxes, no logos, EU warehouse delivery',
      payment: 'Secure Payment', paymentDesc: 'Stripe, PayPal, BIZUM, Klarna',
      returns: '30-Day Returns', returnsDesc: 'Full refund if not satisfied',
      support: '24/7 Support', supportDesc: 'Live chat and WhatsApp available'
    },
    shop: { title: 'Our Collection', filter: 'Filter', sort: 'Sort', all: 'All', silicone: 'Silicone', tpe: 'TPE', realistic: 'Realistic', anime: 'Anime', mini: 'Mini', torso: 'Torso', addToCart: 'Add to Cart', viewDetails: 'View Details', outOfStock: 'Out of Stock', inStock: 'In Stock', height: 'Height', weight: 'Weight', material: 'Material', cupSize: 'Cup Size', skinTone: 'Skin Tone', price: 'Price', quantity: 'Qty', checkout: 'Proceed to Checkout', continueShopping: 'Continue Shopping', emptyCart: 'Your cart is empty', total: 'Total', discount: 'Discount', subtotal: 'Subtotal', featured: 'Featured Products', newArrivals: 'New Arrivals', bestSellers: 'Best Sellers', relatedProducts: 'You May Also Like' },
    brands: { title: 'Our Brands', learnMore: 'Learn More', since: 'Since' },
    about: { title: 'About EuroDolls', mission: 'Our Mission', missionText: 'We bring premium quality love dolls to European customers at fair prices. Our partnerships with leading manufacturers ensure authentic products with full warranty.', factory: 'Factory Partnership', factoryText: 'We work directly with certified factories in China, visiting each facility to verify quality standards and production conditions.', shipping: 'European Warehouse', shippingText: 'Our EU warehouse in Germany enables fast 7-day delivery across Europe with full customs clearance included.' },
    blog: { title: 'Blog & Guides', care: 'Care Guide', careText: 'How to maintain and clean your doll for years of use.', choose: 'How to Choose', chooseText: 'A complete guide to materials, sizes, and features.', shipping: 'Shipping Info', shippingText: 'Everything about discreet shipping and customs.' },
    faq: { title: 'Frequently Asked Questions', q1: 'Is shipping discreet?', a1: 'Yes. All orders ship in plain brown boxes with no logos or branding. The sender shows as "Online Store" and no product information is visible outside.' },
    contact: { title: 'Contact Us', name: 'Name', email: 'Email', message: 'Message', send: 'Send Message', success: 'Message sent! We will reply within 24 hours.' },
    subscribe: { title: 'Get 10% Off', subtitle: 'Subscribe to our newsletter for exclusive deals and care tips.', email: 'Your email address', button: 'Subscribe', success: 'Welcome! Check your inbox for 10% discount code.' },
    footer: { copyright: '© 2026 EuroDolls. All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service', contact: 'Contact' }
  },
  es: {
    nav: { shop: 'Tienda', brands: 'Marcas', blog: 'Blog', about: 'Sobre Nosotros', faq: 'FAQ', cart: 'Carro' },
    hero: { title: 'Muñecas de Amor Premium de Silicona y TPE', subtitle: 'Muñecas de estilo europeo auténtico y anime. Envío discreto por toda Europa. Envío gratis en pedidos superiores a €500.', cta: 'Ver Tienda' },
    trust: { authentic: '100% Auténtico', authenticDesc: 'Directo del fabricante con código anticontrafacción', shipping: 'Envío Discreto', shippingDesc: 'Cajas neutras, sin logotipos, entrega almacén UE', payment: 'Pago Seguro', paymentDesc: 'Stripe, PayPal, BIZUM, Klarna', returns: '30 Días de Devolución', returnsDesc: 'Reembolso completo si no estás satisfecho', support: 'Soporte 24/7', supportDesc: 'Chat en vivo y WhatsApp disponible' },
    shop: { title: 'Nuestra Colección', filter: 'Filtrar', sort: 'Ordenar', all: 'Todos', silicone: 'Silicona', tpe: 'TPE', realistic: 'Realista', anime: 'Anime', mini: 'Mini', torso: 'Torso', addToCart: 'Añadir al Carro', viewDetails: 'Ver Detalles', outOfStock: 'Agotado', inStock: 'En Stock', height: 'Altura', weight: 'Peso', material: 'Material', cupSize: 'Copa', skinTone: 'Tono de Piel', price: 'Precio', quantity: 'Cant.', checkout: 'Proceder al Pago', continueShopping: 'Seguir Comprando', emptyCart: 'Tu carro está vacío', total: 'Total', discount: 'Descuento', subtotal: 'Subtotal', featured: 'Productos Destacados', newArrivals: 'Novedades', bestSellers: 'Los Más Vendidos', relatedProducts: 'También Te Puede Gustar' },
    brands: { title: 'Nuestras Marcas', learnMore: 'Saber Más', since: 'Desde' },
    about: { title: 'Sobre EuroDolls', mission: 'Nuestra Misión', missionText: 'Ofrecemos muñecas de amor premium a precios justos para clientes europeos. Nuestra asociación con fabricantes líderes garantiza productos auténticos con garantía completa.', factory: 'Asociación de Fábrica', factoryText: 'Trabajamos directamente con fábricas certificadas en China, visitando cada instalación para verificar estándares de calidad.', shipping: 'Almacén Europeo', shippingText: 'Nuestro almacén en Alemania permite entrega rápida en 7 días en toda Europa con aduanas incluidas.' },
    blog: { title: 'Blog y Guías', care: 'Guía de Cuidado', careText: 'Cómo mantener y limpiar tu muñeca durante años de uso.', choose: 'Cómo Elegir', chooseText: 'Una guía completa de materiales, tallas y características.', shipping: 'Info de Envío', shippingText: 'Todo sobre envío discreto y aduanas.' },
    faq: { title: 'Preguntas Frecuentes', q1: '¿El envío es discreto?', a1: 'Sí. Todos los pedidos se envían en cajas marrones sin logotipos ni información del producto visible.' },
    contact: { title: 'Contáctanos', name: 'Nombre', email: 'Correo', message: 'Mensaje', send: 'Enviar', success: '¡Mensaje enviado! Responderemos en 24 horas.' },
    subscribe: { title: 'Obtén 10% de Descuento', subtitle: 'Suscríbete para recibir ofertas exclusivas y consejos de cuidado.', email: 'Tu correo electrónico', button: 'Suscribirse', success: '¡Bienvenido! Revisa tu correo para el código de descuento.' },
    footer: { copyright: '© 2026 EuroDolls. Todos los derechos reservados.', privacy: 'Política de Privacidad', terms: 'Términos de Servicio', contact: 'Contacto' }
  },
  pt: {
    nav: { shop: 'Loja', brands: 'Marcas', blog: 'Blog', about: 'Sobre', faq: 'FAQ', cart: 'Carrinho' },
    hero: { title: 'Bonecas de Amor Premium de Silicone e TPE', subtitle: 'Bonecas de estilo europeu autêntico e anime. Envio discreto em toda Europa. Envio grátis em pedidos acima de €500.', cta: 'Ver Loja' },
    trust: { authentic: '100% Autêntico', authenticDesc: 'Direto do fabricante com código anti-falsificação', shipping: 'Envio Discreto', shippingDesc: 'Caixas neutras, sem logotipos, entrega armazém UE', payment: 'Pagamento Seguro', paymentDesc: 'Stripe, PayPal, BIZUM, Klarna', returns: '30 Dias de Devolução', returnsDesc: 'Reembolso total se não ficar satisfeito', support: 'Suporte 24/7', supportDesc: 'Chat ao vivo e WhatsApp disponível' },
    shop: { title: 'Nossa Coleção', filter: 'Filtrar', sort: 'Ordenar', all: 'Todos', silicone: 'Silicone', tpe: 'TPE', realistic: 'Realista', anime: 'Anime', mini: 'Mini', torso: 'Tronco', addToCart: 'Adicionar ao Carrinho', viewDetails: 'Ver Detalhes', outOfStock: 'Esgotado', inStock: 'Em Stock', height: 'Altura', weight: 'Peso', material: 'Material', cupSize: 'Cálice', skinTone: 'Tom de Pele', price: 'Preço', quantity: 'Qtd.', checkout: 'Finalizar Compra', continueShopping: 'Continuar Comprando', emptyCart: 'O seu carrinho está vazio', total: 'Total', discount: 'Desconto', subtotal: 'Subtotal', featured: 'Produtos em Destaque', newArrivals: 'Novidades', bestSellers: 'Mais Vendidos', relatedProducts: 'Você Também Pode Gostar' },
    brands: { title: 'Nossas Marcas', learnMore: 'Saber Mais', since: 'Desde' },
    about: { title: 'Sobre EuroDolls', mission: 'Nossa Missão', missionText: 'Trazemos bonecas de amor premium de qualidade para clientes europeus a preços justos.', factory: 'Parceria de Fábrica', factoryText: 'Trabalhamos diretamente com fábricas certificadas na China, visitando cada instalação.', shipping: 'Armazém Europeu', shippingText: 'Nosso armazém na Alemanha permite entrega rápida em 7 dias em toda a Europa.' },
    blog: { title: 'Blog e Guias', care: 'Guia de Cuidados', careText: 'Como manter e limpar sua boneca por anos de uso.', choose: 'Como Escolher', chooseText: 'Um guia completo de materiais, tamanhos e características.', shipping: 'Info de Envio', shippingText: 'Tudo sobre envio discreto e alfândega.' },
    faq: { title: 'Perguntas Frequentes', q1: 'O envio é discreto?', a1: 'Sim. Todos os pedidos são enviados em caixas castanhas sem logotipos.' },
    contact: { title: 'Contate-nos', name: 'Nome', email: 'Email', message: 'Mensagem', send: 'Enviar', success: 'Mensagem enviada! Responderemos em 24 horas.' },
    subscribe: { title: 'Ganhe 10% de Desconto', subtitle: 'Assine nossa newsletter para ofertas exclusivas e dicas de cuidados.', email: 'Seu endereço de email', button: 'Assinar', success: 'Bem-vindo! Verifique sua caixa de entrada.' },
    footer: { copyright: '© 2026 EuroDolls. Todos os direitos reservados.', privacy: 'Política de Privacidade', terms: 'Termos de Serviço', contact: 'Contato' }
  },
  fr: {
    nav: { shop: 'Boutique', brands: 'Marques', blog: 'Blog', about: 'À propos', faq: 'FAQ', cart: 'Panier' },
    hero: { title: 'Poupées d\'Amour Premium en Silicone et TPE', subtitle: 'Poupées de style européen authentique et anime. Expédition discrète dans toute l\'Europe. Livraison gratuite pour commandes supérieures à €500.', cta: 'Voir la Boutique' },
    trust: { authentic: '100% Authentique', authenticDesc: 'Directement du fabricant avec code anti-contrefaçon', shipping: 'Expédition Discrète', shippingDesc: 'Colis neutres, sans logo, livraison entrepôt UE', payment: 'Paiement Sécurisé', paymentDesc: 'Stripe, PayPal, BIZUM, Klarna', returns: 'Retours 30 Jours', returnsDesc: 'Remboursement complet si non satisfait', support: 'Support 24/7', supportDesc: 'Chat en direct et WhatsApp disponibles' },
    shop: { title: 'Notre Collection', filter: 'Filtrer', sort: 'Trier', all: 'Tous', silicone: 'Silicone', tpe: 'TPE', realistic: 'Réaliste', anime: 'Anime', mini: 'Mini', torso: 'Torse', addToCart: 'Ajouter au Panier', viewDetails: 'Voir Détails', outOfStock: 'Rupture de Stock', inStock: 'En Stock', height: 'Hauteur', weight: 'Poids', material: 'Matériau', cupSize: ' Bonnet', skinTone: 'Teint', price: 'Prix', quantity: 'Qté', checkout: 'Procéder au Paiement', continueShopping: 'Continuer les Achats', emptyCart: 'Votre panier est vide', total: 'Total', discount: 'Remise', subtotal: 'Sous-total', featured: 'Produits en Vedette', newArrivals: 'Nouveautés', bestSellers: 'Les Plus Vendus', relatedProducts: 'Vous Aimerez Aussi' },
    brands: { title: 'Nos Marques', learnMore: 'En Savoir Plus', since: 'Depuis' },
    about: { title: 'À propos d\'EuroDolls', mission: 'Notre Mission', missionText: 'Nous proposons des poupées d\'amour premium de qualité aux clients européens à des prix justes.', factory: 'Partenariat d\'Usine', factoryText: 'Nous travaillons directement avec des usines certifiées en Chine.', shipping: 'Entrepôt Européen', shippingText: 'Notre entrepôt en Allemagne permet une livraison rapide en 7 jours dans toute l\'Europe.' },
    blog: { title: 'Blog et Guides', care: 'Guide d\'Entretien', careText: 'Comment entretenir et nettoyer votre poupée pendant des années.', choose: 'Comment Choisir', chooseText: 'Un guide complet des matériaux, tailles et caractéristiques.', shipping: 'Info Expédition', shippingText: 'Tout sur l\'expédition discrète et les douanes.' },
    faq: { title: 'Questions Fréquentes', q1: 'L\'expédition est-elle discrète?', a1: 'Oui. Toutes les commandes sont expédiées dans des cartons bruns sans logos ni informations visibles.' },
    contact: { title: 'Contactez-nous', name: 'Nom', email: 'Email', message: 'Message', send: 'Envoyer', success: 'Message envoyé! Nous répondrons sous 24 heures.' },
    subscribe: { title: 'Obtenez 10% de Réduction', subtitle: 'Abonnez-vous pour des offres exclusives et des conseils d\'entretien.', email: 'Votre adresse email', button: 'S\'abonner', success: 'Bienvenue! Vérifiez votre boîte de réception.' },
    footer: { copyright: '© 2026 EuroDolls. Tous droits réservés.', privacy: 'Politique de Confidentialité', terms: 'Conditions d\'Utilisation', contact: 'Contact' }
  },
  de: {
    nav: { shop: 'Shop', brands: 'Marken', blog: 'Blog', about: 'Über uns', faq: 'FAQ', cart: 'Warenkorb' },
    hero: { title: 'Premium Silikon- & TPE-Liebespuppen', subtitle: 'Authentische europäische und Anime-Stil Puppen. Diskreter Versand in ganz Europa. Kostenloser Versand ab €500.', cta: 'Zum Shop' },
    trust: { authentic: '100% Authentisch', authenticDesc: 'Direkt vom Hersteller mit Anti-Fälschungs-Code', shipping: 'Diskreter Versand', shippingDesc: 'Neutrale Kartons, kein Logo, EU-Lagerlieferung', payment: 'Sichere Zahlung', paymentDesc: 'Stripe, PayPal, BIZUM, Klarna', returns: '30 Tage Rückgabe', returnsDesc: 'Vollständige Rückerstattung wenn nicht zufrieden', support: '24/7 Support', supportDesc: 'Live-Chat und WhatsApp verfügbar' },
    shop: { title: 'Unsere Kollektion', filter: 'Filtern', sort: 'Sortieren', all: 'Alle', silicone: 'Silikon', tpe: 'TPE', realistic: 'Realistisch', anime: 'Anime', mini: 'Mini', torso: 'Oberkörper', addToCart: 'In den Warenkorb', viewDetails: 'Details', outOfStock: 'Nicht auf Lager', inStock: 'Auf Lager', height: 'Höhe', weight: 'Gewicht', material: 'Material', cupSize: 'Körbchen', skinTone: 'Hautton', price: 'Preis', quantity: 'Menge', checkout: 'Zur Kasse', continueShopping: 'Weiter Einkaufen', emptyCart: 'Ihr Warenkorb ist leer', total: 'Gesamt', discount: 'Rabatt', subtotal: 'Zwischensumme', featured: 'Ausgewählte Produkte', newArrivals: 'Neuheiten', bestSellers: 'Bestseller', relatedProducts: 'Das könnte Ihnen auch gefallen' },
    brands: { title: 'Unsere Marken', learnMore: 'Mehr Erfahren', since: 'Seit' },
    about: { title: 'Über EuroDolls', mission: 'Unsere Mission', missionText: 'Wir bieten Premium-Liebespuppen zu fairen Preisen für europäische Kunden. Unsere Partnerschaften mit führenden Herstellern garantieren authentische Produkte mit voller Garantie.', factory: 'Fabrikpartnerschaft', factoryText: 'Wir arbeiten direkt mit zertifizierten Fabriken in China und besuchen jede Anlage zur Qualitätsprüfung.', shipping: 'EU-Lager', shippingText: 'Unser EU-Lager in Deutschland ermöglicht schnelle 7-Tage-Lieferung in ganz Europa.' },
    blog: { title: 'Blog & Anleitungen', care: 'Pflegeanleitung', careText: 'Wie Sie Ihre Puppe jahrelang pflegen und reinigen.', choose: 'Wie Sie Wählen', chooseText: 'Ein vollständiger Leitfaden zu Materialien, Größen und Funktionen.', shipping: 'Versandinfos', shippingText: 'Alles über diskreten Versand und Zoll.' },
    faq: { title: 'Häufig Gestellte Fragen', q1: 'Ist der Versand diskret?', a1: 'Ja. Alle Bestellungen werden in braunen Kartons ohne Logos oder sichtbare Produktinformationen versandt.' },
    contact: { title: 'Kontaktieren Sie Uns', name: 'Name', email: 'E-Mail', message: 'Nachricht', send: 'Senden', success: 'Nachricht gesendet! Wir antworten innerhalb von 24 Stunden.' },
    subscribe: { title: 'Erhalten Sie 10% Rabatt', subtitle: 'Abonnieren Sie unseren Newsletter für exklusive Angebote und Pflegetipps.', email: 'Ihre E-Mail-Adresse', button: 'Abonnieren', success: 'Willkommen! Prüfen Sie Ihren Posteingang.' },
    footer: { copyright: '© 2026 EuroDolls. Alle Rechte vorbehalten.', privacy: 'Datenschutz', terms: 'AGB', contact: 'Kontakt' }
  }
};

export type Locale = keyof typeof translations;
